"""email_md5_save

Revision ID: 144b6b17fd7a
Revises: 184b87e389e6
Create Date: 2018-09-04 23:38:30.947964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144b6b17fd7a'
down_revision = '184b87e389e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
