"""haha

Revision ID: 184b87e389e6
Revises: 0ae5fa5c1eaf
Create Date: 2018-09-04 23:27:18.494693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184b87e389e6'
down_revision = '0ae5fa5c1eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
